### ISSUE TITLE
Issue On runtime

### ISSUE THREAD

**Issue by talmax1124** [nativefier/nativefier#1136]
~ $ nativefier web.whatsapp.com
zsh: command not found: nativefier
~ $

**Comment by talmax1124** [comment]
Using Big Sur

**Comment by mvastola** [comment]
@talmax1124  Yeah, not sure if the instructions aren't clear or a build step got lost, but in the package directory run:
```bash
npm i
npm run build 
npm i -g
```

I'm actually not sure if the first two are needed, but using all three definitely worked.

**Comment by ronjouch** [comment]
@mvastola unless you're *developing* on Nativefier, the first two lines aren't necessary. As a user, `npm install -g` is enough.

Then, @talmax1124 , your problem is that `nativefier` isn't in your system `$PATH`. Google these and read about it:

- `MacOS How to see my system $PATH`
- `MacOS How to add a path to my system $PATH`
