### ISSUE TITLE
Geforce Now login broken (because parent/child window communication)

### ISSUE THREAD

**Issue by Sekai966** [nativefier/nativefier#1190]
nativefier "play.geforcenow.com" -i "./Pco.ico" -n "Sekai GeForce Now" 

thats what ihve used and it works but when it come to login to start playing i cant login it seems that it cannot connect or smt

![image](https://user-images.githubusercontent.com/70237175/118224771-1707c500-b484-11eb-8f44-9888f5395bfe.png)

![image](https://user-images.githubusercontent.com/70237175/118225147-cd6baa00-b484-11eb-9403-5daae4dcc00b.png)

ihave tried --internal-urls "login.nvidia" to popup the login page but didn't work 

i get this 
![image](https://user-images.githubusercontent.com/70237175/118223890-706ef480-b482-11eb-8222-16701efd1710.png)

any help here ?
iam not that experienced programmer so any help will be appreciated

**Comment by TheCleric** [comment]
Looks like this issue is because of the way Geforce Now has its login window communicate back to the original window. I was able to work around this by disabling electron's window context isolation with the following command to generate the app:

`nativefier https://play.geforcenow.com --name "GeForce NOW" --browserwindow-options '{"webPreferences": {"contextIsolation": false}}'  --internal-urls "nvidia[.]com"`

**Comment by TheCleric** [comment]
Closing this as I haven't heard back. If the workaround doesn't work for you please comment and we can look at reopening. 😄
