### ISSUE TITLE
Cannot see window popup 

### ISSUE THREAD

**Issue by nickbe** [nativefier/nativefier#1197]
I've been trying to nativefy Afterlogic Webmail latelay. If you try this with their webmailer demo from:
https://afterlogic.com/webmail-client you will find the that popup needed to print a mail is opening, but closing immediately again.

![image](https://user-images.githubusercontent.com/10890765/118968182-e2a47500-b96b-11eb-8183-1312d3acc203.png)

Is there some nativefier setting needed here that I'm not aware of?

**Comment by TheCleric** [comment]
Looking into it now, and it may be similar to #1193 in that what's happening in both is that the sites are not asking the app to actually open a window at a URL, but rather asking us to open a "blank" window, that they will then write to. We don't currently support that (for fear that you'll end up with an app that has a bunch of open blank windows hanging out).

Unfortunately the fix there does not work here. Currently looking into how it can be remedied.

**Comment by nickbe** [comment]
Thanks a lot for looking into that Cleric !!

**Comment by nickbe** [comment]
I just saw the #1193 was closed while the issue mentioned above still exists in 12.07.
Or did you already manage to solve the problem otherwise?

**Comment by TheCleric** [comment]
> I just saw the #1193 was closed while the issue mentioned above still exists in 12.07.
> 
> Or did you already manage to solve the problem otherwise?

Not fixed quite yet, but hopefully will have something soon.

**Comment by TheCleric** [comment]
So @nickbe I've finally figured out the root problem causing this, and as well have coded up a fix for it.

You'll have to wait for the code linked above to be approved and a new release, but once that happens here's what you'll need to do:

1. You'll have to use an older version of Electron due to [a bug](https://github.com/electron/electron/issues/28374) in Electron 12.x on how new windows are handled. Technically it works, but you see the print dialog before you see the content which makes it seems as if you are printing a blank page. I successfully got this to work in 11.4.7
2. You'll have to override some options for Electron in the command line

Here's a command that worked successfully for me, but again THIS WILL NOT WORK UNTIL WE GET THE CODE ABOVE RELEASED:

`nativefier https://webmail.afterlogic.com/ -e 11.4.7 --browserwindow-options '{"webPreferences": {"nativeWindowOpen": true}}'`

**Comment by nickbe** [comment]
Very cool Cleric :) Thank you so much for investigating and solving this. 

So the electron version can just be set with the -e switch? Is there some major downside to this older version? something else which we know might or will not work then?

**Comment by TheCleric** [comment]
> Very cool Cleric :) Thank you so much for investigating and solving this.
> 
> So the electron version can just be set with the -e switch? Is there some major downside to this older version? something else which we know might or will not work then?

For our purposes, I don't think so. It may be missing a few bug/security fixes, but I don't think it would be anything major.

**Comment by nickbe** [comment]
Thanks. So just imagine me waiting patiently in an armchair with a glass of scotch. A toast to your work!

**Comment by nickbe** [comment]
Hey Cleric 😄  It actually works now. Thanks for looking into this.

**Comment by likedibao** [comment]
> 



> nativefier https://webmail.afterlogic.com/ -e 11.4.7 --browserwindow-options '{"webPreferences": {"nativeWindowOpen": true}}'

I will report an error when executing this statement 
The error content is Unexpected token ' in JSON at position 0

**Comment by likedibao** [comment]
> nativefier https://webmail.afterlogic.com/ -e 11.4.7 --browserwindow-options '{"webPreferences": {"nativeWindowOpen": true}}'

I will report an error when executing this statement 
The error content is Unexpected token ' in JSON at position 0
Could you tell me how to solve this problem Thankyou!
