### ISSUE TITLE
Nativefier Website broken

### ISSUE THREAD

**Issue by mattruzzi** [nativefier/nativefier#1234]
**Bug description**
https://nativefier.github.io/ returns a 404 and https://nativefier.github.io/nativefier/ uses the gh-pages branch which has an outdated version of the README and a broken image.

**Comment by ronjouch** [comment]
True, and thanks for the heads up.

A few times while cleaning up branches, I wondered what was Jia's plan was about `gh-pages` / the static site, and just shrugged without doing this cleanup. At any rate, as you wrote, it's dead and untouched since 2016.

Now, taking a step back to answer the question *"Should we have a static site for Nativefier that may be friendlier or prettier than the repo page?"*, my answer is no. A standard GitHub repo homepage:

1. Has a layout well-known to many users, giving an immediate familiarity & usability bonus.
2. Is functional, as linking to many useful things (issues, PRs, releases, etc).
3. Is boring but efficient.
4. Encourages contributions, by not shielding visitors from the development side of the project, pushing them to become contributors (and we need these) by giving immediate access to our guts and code.
5. Comes for free with zero maintenance needed.

→ To my eyes, a .github.io vanity page is more costs than benefits. The only added value I see would be to publish docs (API.md) with an automatic TOC on the top+side and maybe a search, but the basic no-fuss dumb file we have now is good enough (ooookaaaay, it's sometimes tedious to synchronize TOC vs contents, whatever :shrug:), and _if_ we did this docs thing, it would have to not regress on the points above. "[Worse is better](https://blog.codinghorror.com/worse-is-better/)" 🙂.

→ I deleted the branch and un-published the site.

With that, closing.

**Comment by mattruzzi** [comment]
I agree that the standard GitHub repo page is good. Should https://nativefier.github.io/ just redirect to https://github.com/nativefier/nativefier#nativefier or is that just unnecessary?

**Comment by ronjouch** [comment]
> I agree that the standard GitHub repo page is good. Should https://nativefier.github.io/ just redirect to https://github.com/nativefier/nativefier#nativefier or is that just unnecessary?

@mattruzzi

1. I don't know how to do this / am not sure redirects are supported by GitHub Pages, do you?
2. Why do you expect https://nativefier.github.io/ to exist? Is it a URL that is referenced somewhere and that we should clean up?
