### ISSUE TITLE
v45.0.0 in macOS 10.15.x breaks new windows/tab functions

### ISSUE THREAD

**Issue by cs-shadowbq** [nativefier/nativefier#1260]
**Homework**

- [x ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ x] I searched existing issues, open & closed. Yes, my bug is new.
- [ x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

v45.0.0 in macOS 10.15.x breaks new tab in windows functions. Using Quip, when I press the "+" button to create a new tab, the window vs tab becomes broken /confusing. The functionality of a single window with multiple tabs no longer works, and spins up additional windows that show as a tab in the main window.

**Steps to reproduce**

```
nativefier -i ./quip.png --name "Quip" --darwin-dark-mode-support --single-instance -f -m --internal-urls "(.*?)" "https://quip.com/"
```

**Expected behavior**

Creating a new tab, only creates 1 additional tab in the existing window. 

**Actual behavior**

Each time a tab is created, 2 tabs are actually created as well as an additional window is created in the background that is linked to one of the tabs. Closing one of the background windows closes all of the windows.

![Screen Shot 2021-07-20 at 10 04 53 AM](https://user-images.githubusercontent.com/77163928/126341723-8a8f3f0b-80d9-473a-991f-202a2a5034fe.png)

* macOS 10.15.7
* `npm outdated -g --depth=0 nativefier` show no outdated tools.
```

nativefier@45.0.0 | MIT | deps: 11 | versions: 105
Wrap web apps natively
https://github.com/nativefier/nativefier

keywords: desktop, electron, app, native, wrapper

bin: nativefier

dist
.tarball: https://registry.npmjs.org/nativefier/-/nativefier-45.0.0.tgz
.shasum: 4dc750d478078d8c8cbdafe1a2273911cea69c8d
.integrity: sha512-StUxs2XrE5Xh1jhikP3979OtNFpIiEOf3GnKMXzvzxgIqmgTPzDeyjWlzCoO+Xxqg8fxqfumLNwgYGx7gVDqQw==
.unpackedSize: 1.1 MB

dependencies:
axios: ^0.21.1              electron-packager: ^15.2.0  gitcloud: ^0.2.3            hasbin: ^1.2.3              loglevel: ^1.7.1            ncp: ^2.0.0                 page-icon: ^0.4.0           sanitize-filename: ^1.6.3   source-map-support: ^0.5.19 tmp: ^0.2.1                 yargs: ^17.0.1

dist-tags:
latest: 45.0.0
```

**Comment by cs-shadowbq** [comment]
Note this is happening in all nativifier URLs on my OSX Catalina platform. Did NOT have this issue prior to 45.0.0

**Comment by cs-shadowbq** [comment]
https://user-images.githubusercontent.com/77163928/127520320-d8d6a4ce-5898-4b2a-8874-61c8dfdd9f5b.mov

**Comment by cs-shadowbq** [comment]
Closing of main window also shows unwanted behavior in https://github.com/nativefier/nativefier/issues/1255

**Comment by TheCleric** [comment]
@cs-shadowbq  I recently found some issues in our window handling logic when fixing some other things. Can you verify that this issue still occurs in the latest Nativefier?

**Comment by cs-shadowbq** [comment]
Issues still occurring in v45.0.4

**Comment by aiyagari** [comment]
This problem just started when I upgraded my builds to 45.0.5 due to the "outdated" message popups.  (used to be on 43.x).  It is happening on Google Docs on Big Sur.  It's very simple to reproduce - even without tabs - just opening in new window causes very strange behavior - the new window is "always on top."  But the OS "sees" both windows as one and when you drag the underlying one, it moves *both* windows!  You *can* type into the bottom window, and you can use both windows if you don't overlap them.  If you try to use tabs, the windows will completely disappear until you Cmd-Tab, at which point they will reappear - but then the only way to use the tab is to drag the tab out to make a window, at which point you still get the behavior mentioned above.

**Comment by aiyagari** [comment]
> This problem just started when I upgraded my builds to 45.0.5 due to the "outdated" message popups. (used to be on 43.x). It is happening on Google Docs on Big Sur. It's very simple to reproduce - even without tabs - just opening in new window causes very strange behavior - the new window is "always on top." But the OS "sees" both windows as one and when you drag the underlying one, it moves _both_ windows! You _can_ type into the bottom window, and you can use both windows if you don't overlap them. If you try to use tabs, the windows will completely disappear until you Cmd-Tab, at which point they will reappear - but then the only way to use the tab is to drag the tab out to make a window, at which point you still get the behavior mentioned above.

I have now verified that this problem was introduced in the 44.x release.  I tried 44.0.7 and it still exhibited the problem (even with using electron 15.x).  However - reverting to 43.1.3 fixed the problem (even though I am still forcing electron 15.3.0).  So it is not a problem with electron, but something introduced in the 44.x release of nativefier.  It is consistent across different apps and can be reproduced by right clicking and choosing "open in new window."

**Comment by cs-shadowbq** [comment]
Something wrong with this logic 

https://github.com/nativefier/nativefier/compare/v43.1.3...v44.0.0  
app/src/components/contextMenu.ts
app/src/helpers/windowHelpers.ts#L85

```ts
export function createNewTab(
  options: WindowOptions,
  setupWindow: (options: WindowOptions, window: BrowserWindow) => void,
  url: string,
  foreground: boolean,
  parent?: BrowserWindow,
): BrowserWindow | undefined {
  log.debug('createNewTab', { url, foreground, parent });
  return withFocusedWindow((focusedWindow) => {
    const newTab = createNewWindow(options, setupWindow, url, parent);
    focusedWindow.addTabbedWindow(newTab);
    if (!foreground) {
      focusedWindow.focus();
    }
    return newTab;
  });
}
```

**Comment by S3basuchian** [comment]
This issue is still present for me in v46.0.4

Is there any workaround?
