### ISSUE TITLE
window.prompt or prompt doesn't work in nativefier

### ISSUE THREAD

**Issue by 0xDante** [nativefier/nativefier#1266]

**Comment by 0xDante** [comment]
the alert and confirm works good only prompt/window.prompt method

**Comment by 0xDante** [comment]
i build a website to desktop app this is the link of the example website :
https://www.javatpoint.com/oprweb/test.jsp?filename=javascript-prompt-dialog-box2
**The website with the browser shows the prompt box but in nativefier no** 
**Here is the picture in browser :**
![Browser capture](https://user-images.githubusercontent.com/88215410/127720214-2b5e9bda-e906-4861-95f8-dc949c4309ad.PNG)
**and here is the picture in nativefier** 
![capture deskop](https://user-images.githubusercontent.com/88215410/127720263-ff6b7e9f-dbbc-44aa-9d39-1d3994134909.PNG)


You can test JavaScript prompt method and you will see the problem , the prompt box don't show up
the alert and confirm works good only prompt/window.prompt method

**Comment by 0xDante** [comment]
i build a website to desktop app this is the link of the example website :
https://www.javatpoint.com/oprweb/test.jsp?filename=javascript-prompt-dialog-box2
**The website with the browser shows the prompt box but in nativefier no** 
**Here is the picture in browser :**
![Browser capture](https://user-images.githubusercontent.com/88215410/127720214-2b5e9bda-e906-4861-95f8-dc949c4309ad.PNG)
**and here is the picture in nativefier** 
![capture deskop](https://user-images.githubusercontent.com/88215410/127720263-ff6b7e9f-dbbc-44aa-9d39-1d3994134909.PNG)


You can test JavaScript prompt method and you will see the problem , the prompt box don't show up
the alert and confirm works good only prompt/window.prompt method

**Comment by TheCleric** [comment]
Because Nativefier is based on Electron, we are limited by the functionality the expose and allow.

In this case Electron has made the decision that `window.prompt` is more harm than good and have stated that it will never be supported. Sorry.

https://github.com/electron/electron/issues/472

Closing this as there's nothing we can do about it, but I'm not happy to be doing it.

Best I can say is if you have control over the site being passed to Nativefier, then avoid using `window.prompt` and instead use some sort of javascript pseudo-prompt such as http://bootboxjs.com/examples.html#bb-prompt
