### ISSUE TITLE
Where does nativefier store data?

### ISSUE THREAD

**Issue by AD1340** [nativefier/nativefier#1281]
Where does nativefier store data? for example like cookies when you login because I wanna know if it saves data in the folder where the app is or not

**Comment by TheCleric** [comment]
It does not save within the app folder by default, (it will save in the OS' user app data folders). You can use the `-p` flag to make it a portable app to store them within the app if you choose, but should be careful about because if you distribute the app with that flag, it will have any cookies or localstorage with it.

**Comment by AD1340** [comment]
> It does not save within the app folder by default, (it will save in the OS' user app data folders). You can use the `-p` flag to make it a portable app to store them within the app if you choose, but should be careful about because if you distribute the app with that flag, it will have any cookies or localstorage with it.

YAY thank u
