### ISSUE TITLE
Cannot login to Google Classroom, because login page opens in browser

### ISSUE THREAD

**Issue by AD1340** [nativefier/nativefier#1369]
when logging in to a cps account on google classroom, when u click sign in, it opens the same login page but in your actual browser. once you login there, it just says there is an unexpected system error plz help

**Comment by Tedward747** [comment]
@AD1340 can you post the command you're using to build the app?

**Comment by AD1340** [comment]
nativefier https://classroom.google.com/

**Comment by Tedward747** [comment]
Can't replicate the problem on my end, what operating system are you using?

run `nativefier https://classroom.google.com/ --name "GoogleClassroom" --verbose` and then start the app through the command prompt instead of clicking on the icon, try to log in, and when it gets to the system error close the app. Copy everything in the command prompt from both commands.

It's going to have a bunch of information that includes your username and folders and such, so my recommendation would be instead of posting it here create a private repository and add a file with everything you copied, and then share the repository with me (Settings -> Collaborators -> Add people, and enter my name).

It's after 2am here so I'm heading to bed, but will take a look in the morning.

**Comment by ronjouch** [comment]
Closing issue as Tedward747 couldn't repro it. OP, feel free to come back with more precise repro steps and we can re-open it.
