### ISSUE TITLE
Nativefier is unmaintained

### ISSUE THREAD

**Issue by jiahaog** [nativefier/nativefier#1577]
**Note:** Nativefier is unmaintained and has been publicly archived. It was built a couple of years ago before the ability to [create shortcuts](https://support.google.com/chrome_webstore/answer/3060053?hl=en) for websites in Chrome, or [similarly](https://support.mozilla.org/en-US/kb/create-desktop-shortcut-website) on Firefox. Users who want to build and use their own website wrappers should strongly prefer these options as they are protected from security vulnerabilities by the browser's self updating mechanism.

Otherwise, if the use case is to build a bespoke app wrapping a website for distribution, consider using Electron directly which offers much more flexibility. 
 
Special thanks goes out to @ronjouch and @TheCleric for keeping the lights on all this time.

**Comment by TheCleric** [comment]
I just wanted to drop a quick note to say how much I appreciate this project and how much of an honor it was to participate in this community, first as a contributor and then as a maintainer.

I know some people may be unhappy with this decision, and it was a tough one for us. We do really feel that for most use cases that what @jiahaog recommends above are better choices. To be perfectly frank, I have been using those over Nativefier for a while due to the ability for the browser to handle security updates. So believe us when we say we're practicing what we preach on this.

Thanks particularly to @jiahaog for getting this project started, @ronjouch for maintaining it (and putting up with my constant need to tweak things), and @mattruzzi who has done a lot of the most recent effort to keep things going.

So long and thanks for all the fish.
