### ISSUE TITLE
"Paste and Match Style" action under macOS: assign it to conventional  Shift + Command + Option + V

### ISSUE THREAD

**Issue by dsemaya** [nativefier/nativefier#404]
### Description
There is no "Paste and Match Style" option in the edit menu on macOS.  Most Mac apps, including Safari and Chrome, have this.  This is problematic for some nativefied web apps where this feature is important. 

### Steps to Reproduce Issue
Use Nativefier to make a Google Docs app
Copy stylized text from another app, such as a browser.   
Attempt to paste into a nativefied version of Google Docs to match style.
Command-shift-V doesn't work, neither does the contextual menu option in Docs because that requires the Docs extension which can't be installed into nativefier.    

### Specifications
- Version of Nativefier 7.4.0
- Version of Node.jsv6.9.1
- OS: macOS 10.12.5
- Architecture x86
- Stack trace from the error message (if any)

**Comment by xldrx** [comment]
https://github.com/jiahaog/nativefier/pull/447

**Comment by kwmc-lucas** [comment]
The key combination for this is wrong, every Apple macOS app uses:
Option + Shift + Command + V

Could you please adopt the standard practice for Nativefier?

I was about to submit this as a bug, because although I could see and use it as an option from the Edit menu, I could never it to work using the keyboard... It didn't cross my mind to double-check the key combination was correct.

**Comment by TheCleric** [comment]
@kwmc-lucas unfortunately that's not true. In doing my research to confirm your statement it seems as if there is a rift over the shortcut on this one across apps:

https://defkey.com/shortcut-actions/paste-and-match-style-109951

Now with XCode saying you are correct, I'm inclined to think Apple agrees with you, it's just not as straightforward as "every" app agrees. This probably is the reason that lead @xldrx to use the command he did. We may be able to support both, but we'd have to choose which one shows in the menu as the "official" shortcut. As well I think we'd need to do some research on what the default key combo (if any) is on Windows/Linux because I'd want to ensure that doesn't get broken in the process.

@ronjouch what say you?

**Comment by ronjouch** [comment]
@TheCleric I say zarroo on this topic, I don't know anything about Macs and what's the reasonable most-conventional thing to do. Up to you 🙂

**Comment by kwmc-lucas** [comment]
@TheCleric sorry if I wasn't clear in my post. I said "every Apple macOS app".

Can you find an **Apple** macOS app that doesn't use the standard combination? I can't.

**Comment by TheCleric** [comment]
> @TheCleric sorry if I wasn't clear in my post. I said "every Apple macOS app".
> 
> Can you find an **Apple** macOS app that doesn't use the standard combination? I can't.


Sorry I missed that clarification. I'm not aware of any but I'm also no expert there. I'll think on this one.

**Comment by kwmc-lucas** [comment]
@TheCleric no problem, I should've been clearer, especially as people used to call them "Apple Macs".

My understanding - and [this article](https://www.themuse.com/advice/copy-paste-same-formatting-trick-how-to-do-it) seems to corroborate - is that the feature originated on macOS _aaaages_ ago, but eventually some apps (Chrome, Firefox) made the feature available on other platforms using an alternative combination, however it's not available across the whole of Windows, unlike macOS, which is the only platform (including Linux) to have it as a standard feature, with an official key combination.

Apple states this in in their [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/) and support article on "[How to copy and paste on Mac](https://support.apple.com/en-us/HT209651)".

Google Chrome has a track record of screwing with Apple's HIG, such as [requiring _holding_ Cmd + Q to quit](https://daringfireball.net/2020/01/quit_confirmation_for_safari_on_macos), which messes up consistency, degrades accessibility, and insidiously creeps into unknowing Chrome-based apps like Edge, which lamentably didn't provide an option to turn that one off.

[DefKey](https://defkey.com/shortcut-actions/paste-and-match-style-109951) shows the anomalous apps stemming from Windows, as the combination is listed as Ctrl + Shift + V, but Macs have a Cmd button. the Mac-native software uses the standard combination as shown.

FWIW I use Firefox and they adhere to the standard, but _I think_ use the alternative on Windows.

I love that nativefier creates an app which feels platform-native, however using a non-standard key combination doesn't provide that experience on macOS, which is the only OS to have have this as a system-wide feature with official documentation on how to implement it.

**Comment by kwmc-lucas** [comment]
@TheCleric @ronjouch thank you ever so much.

**Comment by kwmc-lucas** [comment]
Can confirm this works as expected now 👍
