### ISSUE TITLE
--tray flag causes icon-related startup crash

### ISSUE THREAD

**Issue by alem0lars** [nativefier/nativefier#527]
### Description

When I start an app created with nativefier, I always get the following error:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /home/alem0lars/trello-linux-x64/resources/app/icon.png
    at createTrayIcon (/home/alem0lars/trello-linux-x64/resources/app/lib/webpack:/app/src/components/trayIcon/trayIcon.js:18:21)
    at App.<anonymous> (/home/alem0lars/trello-linux-x64/resources/app/lib/webpack:/app/src/main.js:107:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

### Steps to reproduce issue

Create app:

```
nativefier -p linux -n trello --disable-dev-tools --tray --single-instance --disable-gpu-sandbox --zoom 0.7 https://trello.com
```

Then run it:

```
./trello-linux-x64/trello
```

**Comment by ronjouch** [comment]
@alem0lars thanks for the feedback 👍. Can't reproduce the issue on my (Linux) machine here, though. Can you:

1. Provide the full information requested by the [issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md)
2. Looks like the issue comes from some barf with icon creation. Can you try manually saving a png icon to sisk and passing it using `--icon /path/to/icon.png` ?

**Comment by alem0lars** [comment]
There error disappears if I omit --tray option

Il 27 Gen 2018 22:26, "Ronan Jouchet" <notifications@github.com> ha scritto:

**Comment by Aidoboy** [comment]
I have the same issue when using --tray when creating from this json: 
```
{
	"name": "GroupMe",
	"targetUrl": "https://web.groupme.com/chats",
	"overwrite": true,
	"out": "temp",
	"icon": "resources/IconManager/output/Internet/GroupMe-Icon.ico",
	"tray": true
}
```

It's referencing `C:\Users\Aidan\AppData\Roaming\Nativefier\GroupMe-win32-x64\resources\app\icon.png`, which doesn't exist, instead of `C:\Users\Aidan\AppData\Roaming\Nativefier\GroupMe-win32-x64\resources\app\icon.ico`, which does. Could that be why the error doesn't occur on Linux, @ronjouch?

**Comment by johnathon-b** [comment]
Was having the same issue when doing the --tray command.

Workaround:
Add a --icon "path to .png" to the CLI command and you will no longer get the error.

Example
`nativefier --name "Name" --tray --icon "c:\path\to\icon\icon.png" "https://url/"`

**Comment by copitz** [comment]
It seems like the automatic icon determination doesn't work anymore (tried with gmail and google inbox)

**Comment by ronjouch** [comment]
> *"It seems like the automatic icon determination doesn't work anymore (tried with gmail and google inbox)"*

@copitz yup: https://github.com/jiahaog/nativefier/issues/529 . Just download an icon to a local folder and pass it using the `--icon` flag.

**Comment by dy-dx** [comment]
On mac I also have to copy a png to `MyApp.app/Contents/Resources/app/icon.png` to avoid the crash, because `getAppIcon()` is returning undefined.
See:
https://github.com/jiahaog/nativefier/blob/6dbe4998b6a31767516538970952cef47d7a0c99/app/src/helpers/helpers.ts#L75
and
https://github.com/jiahaog/nativefier/blob/6dbe4998b6a31767516538970952cef47d7a0c99/app/src/components/trayIcon.ts#L12

**Comment by kentcdodds** [comment]
@dy-dx's solution worked for me as well. I also noticed that the `icon.png` needed to be the right size for the menu bar (I think 20px square is the right size). So perhaps the fix here is to accept an additional `--tray-icon` option which defaults to the `--icon` option and is automatically resized?

**Comment by kentcdodds** [comment]
Noticed it also looks a bit pixelated on a retina screen, so 40px square is probably better, but I'm not sure how to specify that it should be scaled to fit. Otherwise I end up with something like this:

![image](https://user-images.githubusercontent.com/1500684/104496220-ee36f800-5595-11eb-9d25-5c36295af29d.png)

**Comment by kentcdodds** [comment]
Thanks 🎉
