### ISSUE TITLE
External login pages open in external browser, breaking login or asking users to know about --internal-urls. Nativefier should automatically open those internally.

### ISSUE THREAD

**Issue by DionGrendelman** [nativefier/nativefier#706]
### Description

Hello i'm trying to use nativefier to login into my youtube music,
But when i click login it opens browser, i login. and nothing happens.

### Steps to reproduce issue

Install it with music.youtube.com

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: nativefier music.youtube.com
- Version of Nativefier (run `nativefier --version`): Current
- Version of node.js (run `node --version`): current
- OS: win 10 64b
- Error message / stack trace (if any):

![afbeelding](https://user-images.githubusercontent.com/22094225/48369705-9e0f3300-e6b7-11e8-9d9f-5b727d5c9786.png)

**Comment by luccasclezar** [comment]
You have to add the Google SignIn url to the internal urls of the app. Use this command:

`nativefier music.youtube.com --internal-urls "(.*?)(accounts\.google\.com/ServiceLogin|music\.youtube\.com)(.*?)"`

With this command you are basically saying that if the url contains "accounts.google.com/ServiceLogin" or "music.youtube.com", it should open inside the app. If you want to add another one, just add the 'other' symbol (`|`) after "music\.youtube\.com" and add the wanted url (without "https://", as the other ones) after it. But remember to escape the dots with a backslash as they mean 'any character' in Regex.

Hope it helps :)

**Comment by ronjouch** [comment]
Thanks @luccasclezar 🙂.

There are lots of similar reports with various sites. A default list of domain / internal-urls pairs, used automatically when nativefying, would be neat. Renaming issue. Help welcome!

**Comment by luccasclezar** [comment]
You're welcome @ronjouch! 🙂

About the fix, wouldn't it be better to add a default list of authentication domains that every nativefied app uses as internal urls? Like Google, Microsoft, Github, etc.

Cause I was thinking about this list of domain / internal-urls pairs and it seems to me that it would be too hard-coded. If all auth domains' urls are internalized, it should be a broader alternative as the list would not be that long and would work with every site that uses these auth providers without the need to hard-code each domain individually.

The only problem with this method that I can think of is the performance of the Regex search (and only because I don't have enough experience with it to know how long the domain list would need to be to slow down the search considerably).

What do you think of this implementation?

**Comment by allo-** [comment]
Isn't this kind of an idea for a second project, which collects nativefier command lines for popular websites?

The first idea I had was "this is something which should not matter, as someone creates a working app once and everybody uses it", but I guess quite a few people here want to nativefy them theirself, so they can trust the binaries. So a collection of command lines would make a nice repo, possibly with a simple script asking ``Which site do you want to nativefy from a template? 1) youtube 2) spotify 3) ...? [Enter a number]``

**Comment by luccasclezar** [comment]
@ronjouch I don't quite get it how there could be false positives. If the auth urls shared their domain with other sites (like Google SignIn having the same domain as another Google site) I would agree with you, but everytime someone access `accounts.google.com/ServiceLogin` it is to Login with Google. I can't think of any false positives in this situation.

But even if there are some false positives, we could simply have a parameter to remove the default auth domains, like `nativefier youtube.com --no-default-auth-urls`. This way if someone had a false positive (which I think it would be rare), it's possible to workaround it.

My main concern about having a list of pairs is that there will always have some sites that won't be in the list and will have to be manually set. In my opinion, the number of people that would have false positives with my suggestion would be far less than the number of people that would have to manually set an auth domain to a random site they want nativefied.

What do you think?

**Comment by luccasclezar** [comment]
I liked @allo-'s idea. And perhaps it would be nice if there was a site or a repository of already compiled binaries of common sites with custom styling (like MacOS's appbar blended with the page's styling, etc).

**Comment by bacongravy** [comment]
I started a personal project along those lines: https://github.com/bacongravy/nativefier-apps

It’s very specific to how I wanted to build the apps; not everyone is going to be using okta for login, for instance.  But it could be forked and made more generic.

The app-specifically settings are in here: https://github.com/bacongravy/nativefier-apps/blob/master/apps.json

**Comment by luccasclezar** [comment]
Ok @ronjouch, I'll give it a look and see what I can do in my spare time 😁

But just to remind you, you didn't answer my question regarding the auth domains issue.

**Comment by bacongravy** [comment]
Another approach would be to change the default regex for internal urls to be something more like `/.*/`.  In terms of trade-offs, it seems to me to be better to live with external urls opening in Nativefier by default than it does to be unable to log-in to some sites by default.

**Comment by bacongravy** [comment]
Or, we could back out #624, I think that's the change that started trigging this problem for some people.

**Comment by luccasclezar** [comment]
@bacongravy In my opinion, the best outcome would be to stay the way it is but to open the auth providers internally by default. I know that would mean we would have to manually add every auth provider we know and possibly add more if someone requested or we discovered a new one, but I don't think that opening all urls internally would be a better choice as a nativefied app should be the closest possible to what a native app would be.

**Comment by bfelbo** [comment]
I'm new to nativefier and I just spent hours struggling with this. Apparently, Github 2 factor auth only works for me when opening as a separate tab (unlike for my coworker).

The developer of the website I was nativefying had never heard of nativefier and definitely hadn't considered released a native app using it. It would be awesome if the most common auth domains could be opened as tabs by default.

**Comment by PhantomNimbi** [comment]
What would be the proper internal url string for "https://www.amazon.com/ap/signin|https://www.audible.com"

Trying to get Audible to open both the login and redirects within the app and although this works I notice it probably isn't entirely correct in format....

I've tried it as "accounts\.amazon\.com/ServiceLogin|\.audible\.com" but that only broke the app.

**Comment by ronjouch** [comment]
> About the fix, wouldn't it be better to add a default list of authentication domains that every nativefied app uses as internal urls? Like Google, Microsoft, Github, etc.

@luccasclezar or anyone: I changed my mind about that, it would be cool, and can be simple to start with, with a list of common auth domains/regexes (google, microsoft, github, etc) to match and to always consider internal, and with logging informing the user about it. PR welcome.

**Comment by bacongravy** [comment]
The following globs capture the authentication domains/paths I know about from this thread:

www.amazon.com/ap/signin
www.google.com/accounts
accounts.google.com/
*.okta.com/

What else would we want in the initial list?

**Comment by bfelbo** [comment]
I think you'd also want to add GitHub, which is used as sign-in for many tools.

Perhaps also LinkedIn, Microsoft, Twitter, and Facebook if you want to support non-developer websites.

**Comment by bacongravy** [comment]
Those all sound good to me.  If someone knows the domain names / URLs for them please add them to this thread.

**Comment by avlm** [comment]
Hi! Today I tried to nativefy Notion, got the same problem while using google to log in. Here's the command I used:
```
nativefier --name "Notion" --internal-urls "(.*?)(accounts\.google\.com/ServiceLogin|notion\.so)(.*?)" --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "notion.so"
```
It didn't work, even if I use `--internal-urls` and `--user-agent`

Appreciate any help, I'm going to create a password so I can log in without google services, but use google or other services to log in is a great convenience.

Available to help with anything I can.

Thanks!

**Comment by CocoThePimp** [comment]
> Hi! Today I tried to nativefy Notion, got the same problem while using google to log in. Here's the command I used:
> 
> ```
> nativefier --name "Notion" --internal-urls "(.*?)(accounts\.google\.com/ServiceLogin|notion\.so)(.*?)" --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "notion.so"
> ```
> 
> It didn't work, even if I use `--internal-urls` and `--user-agent`
> 
> Appreciate any help, I'm going to create a password so I can log in without google services, but use google or other services to log in is a great convenience.
> 
> Available to help with anything I can.
> 
> Thanks!

I got the same issue, but if you sign up with google, and then create a new account (with password) with the same google's email, it will be linked ;). So it's fine !

**Comment by jharohit466** [comment]
This method worked for me 
[https://stackoverflow.com/questions/62128548/how-to-force-to-open-all-links-in-same-window-in-nativefier](url)


Short Example (What I did):

`GOTO> /home/username/Nativefier-Apps/YouTube/`
`GOTO> resources folder` for me it is inside `YouTube-linux-x64` under `YouTube` folder
`GOTO> app` open `nativefier.json` with any text editor [I used `Visual Studio Code`] 
`FIND> "internalUrls"` and replace `null` with the list of URL you want to open internally e.g `"(.*?contacts\\.google\\.com.*?|.*?accounts\\.google\\.com*?)"` 

I'm not sure if I can post it here. But I thought this may help contributors or developers.

**Comment by TheCleric** [comment]
> I changed my mind about that, it would be cool, and can be simple to start with, with a list of common auth domains/regexes (google, microsoft, github, etc) to match and to always consider internal, and with logging informing the user about it. PR welcome.

@ronjouch would this be something we'd want configurable? Like maybe a `--internal-login` cli param that defaults to true to cut down on issues like these, but could be turned off by a user if it causes an issue?

**Comment by ronjouch** [comment]
> > I changed my mind about that, it would be cool, and can be simple to start with, with a list of common auth domains/regexes (google, microsoft, github, etc) to match and to always consider internal, and with logging informing the user about it. PR welcome.
> 
> @ronjouch would this be something we'd want configurable? Like maybe a `--internal-login` cli param that defaults to true to cut down on issues like these, but could be turned off by a user if it causes an issue?

@TheCleric yup, agreed with you that this one does need an extra flag, to let users opt out in case of inevitable problems.

But I'm not the most involved in the problem here. Passersby/commenters @bacongravy @luccasclezar @bacongravy @bfelbo: does the suggestion made by @TheCleric make sense?

- As suggested above, Nativefier would include a hardcoded list of common login providers (Amazon, Google, Okta, LinkedIn, Microsoft, Twitter, Facebook, etc), that it would by default consider internal.
    - This list will be a mix of domains, and URL prefixes. Preferably non-root-domains, or URL prefixes, for maximum precision (you want foo.com to consider auth.facebook.com internal, not whole facebook.com)
- A new flag `--internal-login-pages` (defaulting to true) would allow *disabling* this new behavior if set to `false`.
  - Does this make sense? Would you have offered a different kind of configurability? Does this fit use cases of yours, and that you imagine?
- It would be documented a breaking change, with a new major version, and a mention about the opt-out flag.

---

**Out of scope / off-topic**: I also like the idea surfaced above to have a repo to centralize configs per website, helping new users easily get a working app (looking at you, WhatsApp). But this is another discussion, and there will always be sites missing custom settings, so even if/when we have this settings repo, the new "consider common auth providers as internal" code will remain useful, and valuable by default.

By the way, Nativefier already has such a repo for icons with [nativefier-icons](https://github.com/nativefier/nativefier-icons) + [gitcloud](https://github.com/nativefier/gitcloud) (and it's weird, needs work, and I'm lagging on merging PRs). We could generalize it into new general "icons + conf + js/css injects" repo+logic, offered interactively to users at build time. But again, let's stay on topic.

---

@TheCleric also, I like that you picked a name that starts with `--internal`, because we want it clustered / documented next to `--internal-urls`. But the whole `--internal-login` isn't super clear on first read about what it does. What about `--internal-login-pages` ?

**Comment by TheCleric** [comment]
> also, I like that you picked a name that starts with --internal, because we want it clustered / documented next to --internal-urls. But the whole --internal-login isn't super clear on first read about what it does. What about --internal-login-pages ?

@ronjouch yep, that's fine. I wasn't picky about the exact name. 😄

**Comment by ronjouch** [comment]
Released in https://github.com/nativefier/nativefier/releases/tag/v43.0.0 ! Thanks @TheCleric !
