### ISSUE TITLE
Shows blank page making new thelounge nativefier

### ISSUE THREAD

**Issue by arch1mede** [nativefier/nativefier#730]
### Description

I run thelounge (irc client) on a VM that I can access doing https://192.168.1.233:9000

### Details

- Are you nativefying a *public* website? No?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>` nativefier --name IRC https://192.168.1.233:9000
- Version of Nativefier (run `nativefier --version`): 7.6.9
- Version of node.js (run `node --version`): 10.5.9`
- OS: WIN10
- Error message / stack trace (if any): I don't see any and I don't know where to look for logs

**Comment by ronjouch** [comment]
@arch1mede I think this is fixed, because a more recent issue, https://github.com/nativefier/nativefier/issues/1091 , complains that notifications are broken in a nativefied TheLounge. Feel free to follow the other issues about that other issue, but closing this issue.

Do shout if I'm missing something (if your blank page issue persists) and we'll re-open.
