### ISSUE TITLE
Keeping settings when generating an app for the same URL

### ISSUE THREAD

**Issue by vinifmor** [nativefier/nativefier#884]
### Description

It is preserving the previous settings for a given URL even when you specify different ones.

### Steps to reproduce issue
Example:
1) **nativefier https://hangouts.google.com --maximize -name hangouts**
2) open the app and then remove the generated folder
3) execute the same process again with different options: **nativefier https://hangouts.google.com --clear-cache -name hangouts**
4) open the app and it will be maximized again

### Details
- Version of Nativefier: **v7.7.0**
- Version of node.js: **v12.13.1**
- OS: **Manjaro Linux**

**Comment by sorhtyre** [comment]
This issue seems to stem from prepareElectronApp.ts line 107: `hash.update(url);`

Under Linux, temp application configurations are maintained in ~/.config
Because nativefier uses a static hash function (dependant on URL), the application will always generate the same name (hangouts-nativefier-xxxxxx). Thus, your app will always use the same folder for temp configurations.

There are two fixes.
1. Manual deletion of the application's configuration folder
2. Modify the nativefier hash function to include additional dynamic input

**Comment by ronjouch** [comment]
@sorhtyre is right, this is intentional behavior (and also, note that changing options not persisted to Electron state *is* honored, you are just stumbling on a very specific corner case). Just cleanup the config folder for your app.
